package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"database/sql"
	"fmt"

	"go.infratographer.com/permissions-api/pkg/permissions"
	"go.infratographer.com/x/gidx"

	"go.infratographer.com/metadata-api/internal/ent/generated"
	"go.infratographer.com/metadata-api/internal/ent/generated/annotation"
)

// AnnotationNamespaceCreate is the resolver for the annotationNamespaceCreate field.
func (r *mutationResolver) AnnotationNamespaceCreate(ctx context.Context, input generated.CreateAnnotationNamespaceInput) (*AnnotationNamespaceCreatePayload, error) {
	if err := permissions.CheckAccess(ctx, input.OwnerID, actionMetadataAnnotationNamespaceUpdate); err != nil {
		return nil, err
	}

	ns, err := r.client.AnnotationNamespace.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &AnnotationNamespaceCreatePayload{AnnotationNamespace: ns}, nil
}

// AnnotationNamespaceDelete is the resolver for the annotationNamespaceDelete field.
func (r *mutationResolver) AnnotationNamespaceDelete(ctx context.Context, id gidx.PrefixedID, force bool) (*AnnotationNamespaceDeletePayload, error) {
	if err := permissions.CheckAccess(ctx, id, actionMetadataAnnotationNamespaceUpdate); err != nil {
		return nil, err
	}

	tx, err := r.client.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, err
	}

	defer tx.Rollback()

	annotations, err := tx.Annotation.Query().Where(annotation.AnnotationNamespaceID(id)).All(ctx)
	if err != nil {
		return nil, err
	}

	antCount := len(annotations)
	if antCount != 0 {
		if force {
			antCount := 0
			for _, ant := range annotations {
				// TODO - :bug: - must delete one-by-one to ensure the deleted ID is available when the delete eventhook is triggered
				// r.client.Annotation.Delete().Where(annotation.AnnotationNamespaceID(id)).Exec(ctx)
				if err := tx.Annotation.DeleteOneID(ant.ID).Exec(ctx); err != nil {
					return nil, err
				}
				antCount++
			}
		} else {
			return nil, fmt.Errorf("annotation namespace is in use and can't be deleted")
		}
	}

	if err := tx.AnnotationNamespace.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return &AnnotationNamespaceDeletePayload{DeletedID: id, AnnotationDeletedCount: antCount}, nil
}

// AnnotationNamespaceUpdate is the resolver for the annotationNamespaceUpdate field.
func (r *mutationResolver) AnnotationNamespaceUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateAnnotationNamespaceInput) (*AnnotationNamespaceUpdatePayload, error) {
	if err := permissions.CheckAccess(ctx, id, actionMetadataAnnotationNamespaceUpdate); err != nil {
		return nil, err
	}

	ns, err := r.client.AnnotationNamespace.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	ns, err = ns.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &AnnotationNamespaceUpdatePayload{AnnotationNamespace: ns}, nil
}

// AnnotationNamespace is the resolver for the annotationNamespace field.
func (r *queryResolver) AnnotationNamespace(ctx context.Context, id gidx.PrefixedID) (*generated.AnnotationNamespace, error) {
	if err := permissions.CheckAccess(ctx, id, actionMetadataAnnotationNamespaceUpdate); err != nil {
		return nil, err
	}

	return r.client.AnnotationNamespace.Get(ctx, id)
}
